// Vellum Codex - Books Data
var authorGenreMap = {
  "George Orwell": "Dystopian",
  "Brandon Sanderson": "Fantasy",
  "Leo Tolstoy": "Classic",
  "Charles Dickens": "Classic",
  "Fyodor Dostoevsky": "Classic",
  "Haruki Murakami": "Literary Fiction",
  "Harper Lee": "Literary Fiction",
  "Victor Hugo": "Classic",
  "Agatha Christie": "Mystery",
  "Homer": "Classic",
  "Oscar Wilde": "Classic",
  "James Joyce": "Classic",
  "Albert Camus": "Philosophy",
  "Franz Kafka": "Philosophy",
  "Bram Stoker": "Horror",
  "Mary Shelley": "Horror",
  "H. G. Wells": "Sci-Fi",
  "Rafael Sabatini": "Historical Fiction",
  "Tomasi di Lampedusa": "Historical Fiction",
  "Liviu Rebreanu": "Historical Fiction",
  "William Shakespeare": "Classic",
  "Mikhail Bulgakov": "Literary Fiction",
  "Mihaly Csikszentmihalyi": "Self-Help",
  "Antony Beevor": "History",
  "A. P. J. Abdul Kalam": "Biography",
  "Bear Grylls": "Biography",
  "Elie Wiesel": "Biography",
  "Clive Cussler": "Adventure",
  "George R. R. Martin": "Fantasy",
  "Karl Marx": "History",
  "William Shirer": "History",
  "G. J. Meyer": "History",
  "Mark Mazower": "History",
  "Alan Clark": "History",
  "Isabel Allende": "Literary Fiction",
  "Virginia Woolf": "Classic",
  "Rainer Maria Rilke": "Philosophy",
  "Thomas Hardy": "Classic",
  "Evan Winter": "Fantasy",
  "Kristen Ciccarelli": "Fantasy",
  "M. L. Wang": "Fantasy",
  "Robert Jackson Bennett": "Fantasy",
  "Jennifer Giesbrecht": "Fantasy",
  "Liz Moore": "Mystery",
  "Richard Osman": "Mystery",
  "Daniel Defoe": "Classic",
  "Alexandre Dumas": "Classic",
  "Khaled Hosseini": "Literary Fiction",
  "F. Scott Fitzgerald": "Literary Fiction",
  "J. L. Carr": "Literary Fiction",
  "Miguel de Cervantes": "Classic",
  "Voltaire": "Philosophy",
  "M. L. Rio": "Literary Fiction",
  "Antal Szerb": "Literary Fiction",
  "Claire Keegan": "Literary Fiction",
  "George and Weedon Grossmith": "Humor"
};

function getGenre(author) {
  return authorGenreMap[author] || "Literary Fiction";
}

// Books array
window.books = [
  {title: "Animal Farm", author: "George Orwell", image: "animal farm.jpg", genre: "Dystopian"},
  {title: "1984", author: "George Orwell", image: "1984.jpg", genre: "Dystopian"},
  {title: "The God of the Woods", author: "Liz Moore", image: "god of the woods.jpg", genre: "Mystery"},
  {title: "Stranger", author: "Albert Camus", image: "stranger.jpg", genre: "Philosophy"},
  {title: "We Solve Murders", author: "Richard Osman", image: "we solve murders.jpg", genre: "Mystery"},
  {title: "Robinson Crusoe", author: "Daniel Defoe", image: "robinson crusoe.jpg", genre: "Classic"},
  {title: "Count of Monte Cristo", author: "Alexandre Dumas", image: "count of monte cristo.jpg", genre: "Classic"},
  {title: "Crime and Punishment", author: "Fyodor Dostoevsky", image: "crime and punishment.jpg", genre: "Classic"},
  {title: "Norwegian Wood", author: "Haruki Murakami", image: "norwegian wood.jpg", genre: "Literary Fiction"},
  {title: "To Kill a Mocking Bird", author: "Harper Lee", image: "to kill a mocking bird.jpg", genre: "Literary Fiction"},
  {title: "Anna Karenina", author: "Leo Tolstoy", image: "anna karenina.jpg", genre: "Classic"},
  {title: "Great Gatsby", author: "F. Scott Fitzgerald", image: "great gatsby.jpg", genre: "Literary Fiction"},
  {title: "Tress of the Emerald Sea", author: "Brandon Sanderson", image: "tress of emerald sea.jpg", genre: "Fantasy"},
  {title: "A Month in the Country", author: "J. L. Carr", image: "a month in the country.jpg", genre: "Literary Fiction"},
  {title: "A Tale of Two Cities", author: "Charles Dickens", image: "tale of two cities.jpg", genre: "Classic"},
  {title: "Don Quixote", author: "Miguel de Cervantes", image: "don quixote.jpg", genre: "Classic"},
  {title: "And Then There Were None", author: "Agatha Christie", image: "and then there were none.jpg", genre: "Mystery"},
  {title: "Kite Runner", author: "Khaled Hosseini", image: "kite runner.jpg", genre: "Literary Fiction"},
  {title: "War and Peace", author: "Leo Tolstoy", image: "war and peace.jpg", genre: "Classic"},
  {title: "Night", author: "Elie Wiesel", image: "night.jpg", genre: "Biography"},
  {title: "Dracula", author: "Bram Stoker", image: "dracula final.jpg", genre: "Horror"},
  {title: "Small Things Like These", author: "Claire Keegan", image: "small things like these.jpg", genre: "Literary Fiction"},
  {title: "Rise and Fall of the Third Reich", author: "William Shirer", image: "rise and fall.jpg", genre: "History"},
  {title: "The Leopard", author: "Tomasi di Lampedusa", image: "leopard.jpg", genre: "Historical Fiction"},
  {title: "Captain Blood", author: "Rafael Sabatini", image: "captain blood.jpg", genre: "Historical Fiction"},
  {title: "Metamorphosis", author: "Franz Kafka", image: "metamorphosis.jpg", genre: "Philosophy"},
  {title: "White Nights", author: "Fyodor Dostoevsky", image: "white nights.jpg", genre: "Classic"},
  {title: "Hard Times", author: "Charles Dickens", image: "hard times.jpg", genre: "Classic"},
  {title: "The Ice Dragon", author: "George R. R. Martin", image: "ice dragon.jpg", genre: "Fantasy"},
  {title: "Flow", author: "Mihaly Csikszentmihalyi", image: "flow.jpg", genre: "Self-Help"},
  {title: "The Second World War", author: "Antony Beevor", image: "2nd ww.jpg", genre: "History"},
  {title: "A World Undone", author: "G. J. Meyer", image: "world undone.jpg", genre: "History"},
  {title: "My Journey", author: "A. P. J. Abdul Kalam", image: "my journey.jpg", genre: "Biography"},
  {title: "The Rage of Dragons", author: "Evan Winter", image: "rage of dragons.jpg", genre: "Fantasy"},
  {title: "Crimsom Moth", author: "Kristen Ciccarelli", image: "crimson moth.jpg", genre: "Fantasy"},
  {title: "Mistborn", author: "Brandon Sanderson", image: "mistborn.jpg", genre: "Fantasy"},
  {title: "If We Were Villains", author: "M. L. Rio", image: "if we were villains.jpg", genre: "Literary Fiction"},
  {title: "The Tainted Cup", author: "Robert Jackson Bennett", image: "tainted cup.jpg", genre: "Fantasy"},
  {title: "The Sword of Kaigen", author: "M. L. Wang", image: "sword of kaigen.jpg", genre: "Fantasy"},
  {title: "Blood Over Bright Haven", author: "M. L. Wang", image: "blood over bright haven.jpg", genre: "Fantasy"},
  {title: "Candide", author: "Voltaire", image: "candide.jpg", genre: "Philosophy"},
  {title: "Forest of the Hanged", author: "Liviu Rebreanu", image: "forest of the hanged.jpg", genre: "Historical Fiction"},
  {title: "The Master and Margarita", author: "Mikhail Bulgakov", image: "master and margarita.jpg", genre: "Literary Fiction"},
  {title: "The Trial", author: "Franz Kafka", image: "trial.jpg", genre: "Philosophy"},
  {title: "The Brothers Karamazov", author: "Fyodor Dostoevsky", image: "brothers.jpg", genre: "Classic"},
  {title: "Journey by moonlight", author: "Antal Szerb", image: "journey by moonlight.jpg", genre: "Literary Fiction"},
  {title: "Dubliners", author: "James Joyce", image: "dubliners.jpg", genre: "Classic"},
  {title: "The Picture of Dorian Gray", author: "Oscar Wilde", image: "picture of dorian gray.jpg", genre: "Classic"},
  {title: "Mud, Sweat, and Tears", author: "Bear Grylls", image: "mud sweat tears bear grylls.jpg", genre: "Biography"},
  {title: "Valhalla Rising", author: "Clive Cussler", image: "valhalla rising.jpg", genre: "Adventure"},
  {title: "Poseidon's Arrow", author: "Clive Cussler", image: "Poseidons arrow.jpg", genre: "Adventure"},
  {title: "The Balkans", author: "Mark Mazower", image: "balkans.jpg", genre: "History"},
  {title: "Richard II", author: "William Shakespeare", image: "richard 2.jpg", genre: "Classic"},
  {title: "The Diary of a Nobody", author: "George and Weedon Grossmith", image: "diary of nobody.jpg", genre: "Humor"},
  {title: "Trojan Odyssey", author: "Clive Cussler", image: "trojan odyssey.jpg", genre: "Adventure"},
  {title: "Barbarossa", author: "Alan Clark", image: "barbarrosa.jpg", genre: "History"},
  {title: "Deceits of Time", author: "Isabel Allende", image: "deceits of time.jpg", genre: "Literary Fiction"},
  {title: "To the Lighthouse", author: "Virginia Woolf", image: "to the lighthouse.jpg", genre: "Classic"},
  {title: "Letters to a Young Poet", author: "Rainer Maria Rilke", image: "letters to a young poet.jpg", genre: "Philosophy"},
  {title: "Great Expectations", author: "Charles Dickens", image: "great expectations.webp", genre: "Classic"},
  {title: "The Iliad", author: "Homer", image: "iliad homer.jpeg", genre: "Classic"},
  {title: "The Odyssey", author: "Homer", image: "odyssey homer.avif", genre: "Classic"},
  {title: "Les Misérables", author: "Victor Hugo", image: "les miserables.jpg", genre: "Classic"},
  {title: "Frankenstein", author: "Mary Shelley", image: "frankenstein.jpg", genre: "Horror"},
  {title: "Tess of the d'Urbervilles", author: "Thomas Hardy", image: "tess of urbervilles.jpg", genre: "Classic"},
  {title: "The Time Machine", author: "H. G. Wells", image: "time machine.jpg", genre: "Sci-Fi"},
  {title: "The Communist Manifesto", author: "Karl Marx", image: "communist manifesto.jpg", genre: "History"}
];